### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by chuse4096** [ferru97/PyPaperBot#8]
Apologies to not getting back to you sooner.

I switched to a different computer and managed to get two separate downloads to my specified directory. Only thing is, I now have two instances of a 'bibtex.bib' and a excel filed named 'result,' which is simply the book's information in each separate field. 

Tried changing the download directory, and used a different DOI from a different article: same result, same two files. Any help would be appreciated

**Comment by ferru97** [comment]
Hi @chuse4096 
No problem, I thought you solved

So if I understand correctly the only thing that the tool generates you are bibtex. and result.csv but never the PDF of the paper. Let me precise some things:
1. Make sure that the download directory is empty or do not have previously downloaded _bibtex.bib_ and _result.csv_ since they may be overwritten or the tool may not have the permission to overwite (I'll fix this in the next version)
2. Sometimes can happen that the tool does not find the paper on schihub when downloading by DOI
3. When downloading by DOI it is assumed that access to scihub is not blocked in your country, otherwise, you should use a VPN. To check this try to go on https://sci-hub.tw/ and see if the site is available.

To help me debugging you can send to me privately te _result.csv_ files at vitof970@gmail.com so I can check the information there

**Comment by chuse4096** [comment]
Thanks for the fast response,

I downloaded the first DOI onto my desktop, which is quite populated. Also, I live in America, and am using Jstor's site for both files. I'll send the _results.csv_ files for you to take a gander at. I just tried a DOI from PubMed in my Downloads, same issue.

**Comment by ferru97** [comment]
Solved privately

**Comment by kir-malishev** [comment]
Hello. 

Having the same issue, you can see at https://github.com/ferru97/PyPaperBot/issues/20 that there should have been over 200 articles downloaded. But not a single one was downloaded. I tried to run the script on 3 DOIs. In result.csv, all articles had False in the Downloaded column. At the same time, the information about the articles and Bibtex was received correctly. This is hardly a normal situation. I want to note that downloading articles via --query works correctly.
